---
sample_rate: 44100
clip_duration: 2.
max_caption_len: 10

train_datasets:
    FreeSpokenDigit:
        root: "/datasets/free-spoken-digit-dataset"
        split: "train"

test_datasets:
    FreeSpokenDigit:
        root: "/datasets/free-spoken-digit-dataset"
        split: "test"
        
audio_codec:
    name: DAC
    n_quantizers: 2

tokenizer:
    name: BertDAC

llm:
    name: Llama
    trainable: True
    block_size: 384  # Maximize block size
    vocab_size:  # Leave blank. Parsed later from len(tokenier)
    n_layer: 12
    n_head: 12
    n_embd: 768
    
train:
    device: "cuda"
    num_workers: 16
    loss: ce_loss
    optimizer: AdamW
    lr: 1e-4
    warm_up_steps: 1000  # Leave blank if no warm up is used
    batch_size_per_device: 4
    test_every_n_steps: 1000
    save_every_n_steps: 2000
    training_steps: 10000
    resume_ckpt_path:  # Leave blank if train from scratch